services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    image: pedido-frontend:latest
    ports:
      - '80:80'
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - PEDIDO_API_URL=http://localhost:8081      - PEDIDOS_ENDPOINT=/orders